import images from "./images";

console.log(images, '🛎')

// const categoryData = [
//   {
//     id: 1,
//     name: 'Breakfast',
//     icon: icons.rice_bowl,
//   },
//   {
//     id: 2,
//     name: 'Lunch',
//     icon: icons.noodle,
//   },
//   {
//     id: 3,
//     name: 'Dinner',
//     icon: icons.hotdog,
//   },
//   {
//     id: 4,
//     name: 'Snacks',
//     icon: icons.salad,
//   },
// ];

// price rating
const affordable = 1;
const fairPrice = 2;
const expensive = 3;

const foodData = [
  {
    id: 1,
    name: 'Chilli Con Carne',
    rating: 4.8,
    categories: [3],
    priceRating: affordable,
    photo: images.chilli_concarne,
    duration: '30 - 45 min',
    menu: [
      {
        menuId: 1,
        name: 'Chilli Con Carne',
        photo: images.chilli_concarne,
        description:
          'Lean beef mince with wildrice, basmati rice, red chilli, salt, pepper, garlic, kidney beans, carrots and white onion',
        calories: 598,
        price: 8.95,
        carbs: 71,
        protien: 48.8,
        fats: 6.7,
      },
      {
        menuId: 1.1,
        name: 'Quorn Chilli Con Carne',
        photo: images.quorn_chilli,
        description:
          'Lean beef mince with wildrice, basmati rice, red chilli, salt, pepper, garlic, kidney beans, carrots and white onion',
        calories: 375,
        price: 7.95,
        carbs: 14,
        protien: 48,
        fats: 15,
      },
    ],
  },
  {
    id: 2,
    name: 'Beef Stew & Dumplings',
    rating: 4.8,
    categories: [3],
    priceRating: expensive,
    photo: images.beef_stew_dumplings,
    duration: '15 - 20 min',
    menu: [
      {
        menuId: 2,
        name: 'Beef Stew & Dumplings',
        photo: images.beef_stew_dumplings,
        description:
          'Beef, carrots, onions, mushrooms, gravy granules, plain flour, baking powder, himalayan salt, pepper, thyme and rosemary',
        calories: 250,
        price: 8.95,
        carbs: 14,
        protien: 48,
        fats: 15,
      },
    ],
  },
  {
    id: 3,
    name: 'Tofu Thai Curry',
    rating: 4.8,
    categories: [2],
    priceRating: expensive,
    photo: images.tofu_thai_curry,
    duration: '20 - 25 min',
    menu: [
      {
        menuId: 3,
        name: 'Tofu Thai Curry',
        photo: images.tofu_thai_curry,
        description:
          'Carrots, lemon grass, butternut squash, tofu, chickpeas, olive oil, red pepper, himalayan salt, lime, spring onion',
        calories: 306,
        price: 8.95,
        carbs: 40,
        protien: 40,
        fats: 11.7,
      },
    ],
  },
  {
    id: 4,
    name: 'Cajun Salmon',
    rating: 4.8,
    categories: [2, 3],
    priceRating: expensive,
    photo: images.cajun_salmon,
    duration: '10 - 15 min',

    menu: [
      {
        menuId: 4,
        name: 'Cajun Salmon',
        photo: images.cajun_salmon,
        description: 'salon, olive, spinach, sweet potato, broccoli',
        calories: 339,
        price: 10.95,
        carbs: 28.6,
        protien: 20.6,
        fats: 5.5,
      },
    ],
  },
  {
    id: 5,
    name: 'Pesto Chicken Pasta',
    rating: 4.8,
    categories: [2],
    priceRating: affordable,
    photo: images.pesto_chicken,
    duration: '15 - 20 min',
    menu: [
      {
        menuId: 5,
        name: 'Pesto Chicken Pasta',
        photo: images.pesto_chicken,
        description: 'chicken breast, cherry tomatoes, pasta',
        calories: 200,
        price: 8.95,
        carbs: 33.8,
        protien: 38.6,
        fats: 2.7,
      },
    ],
  },
  {
    id: 6,
    name: 'Blueberry Pancakes',
    rating: 4.9,
    categories: [1],
    priceRating: affordable,
    photo: images.blueberry_pancake,
    duration: '35 - 40 min',
    menu: [
      {
        menuId: 6,
        name: 'Blueberry Pancakes',
        photo: images.blueberry_pancake,
        description: 'PhD Diet Vanilla Whey, Blueberry',
        calories: 478,
        price: 4.95,
        carbs: 60,
        protien: 32,
        fats: 8.6,
      },
    ],
  },
  {
    id: 7,
    name: 'Bananna Pancakes',
    rating: 4.9,
    categories: [1],
    priceRating: affordable,
    photo: images.bananna_pancake,
    duration: '35 - 40 min',
    menu: [
      {
        menuId: 7,
        name: 'Bananna Pancakes',
        photo: images.bananna_pancake,
        description: 'PhD Diet Vanilla Whey, Bananna',
        calories: 505,
        price: 4.95,
        carbs: 62,
        protien: 36,
        fats: 13,
      },
    ],
  },
  {
    id: 8,
    name: 'Vegan Bananna Pancakes',
    rating: 4.9,
    categories: [1],
    priceRating: affordable,
    photo: images.vegan_bananna_pancake,
    duration: '35 - 40 min',

    menu: [
      {
        menuId: 8,
        name: 'Vegan Bananna Pancakes',
        photo: images.vegan_bananna_pancake,
        description: 'Plain Flour, baking powder, coconut milk, Bananna',
        calories: 311,
        price: 4.95,
        carbs: 58,
        protien: 9,
        fats: 2,
      },
    ],
  },
  {
    id: 9,
    name: 'Teriyaki Beef',
    rating: 4.9,
    categories: [3],
    priceRating: affordable,
    photo: images.teriyaki_beef,
    duration: '35 - 40 min',
    menu: [
      {
        menuId: 9,
        name: 'Teriyaki Beef',
        photo: images.teriyaki_beef,
        description: 'Beef steak, whole wheat noodles, brocolli, spinach',
        calories: 380,
        price: 8.95,
        carbs: 45,
        protien: 30,
        fats: 5.2,
      },
    ],
  },
  {
    id: 10,
    name: 'Granola',
    rating: 4.9,
    categories: [1, 4],
    priceRating: affordable,
    photo: images.granola,
    duration: '35 - 40 min',
    menu: [
      {
        menuId: 10,
        name: 'Granola',
        photo: images.granola,
        description: 'Oats, sultanas, sunflower oil, agave nectar',
        calories: 461,
        price: 4.95,
        carbs: 95,
        protien: 12.4,
        fats: 9.8,
      },
    ],
  },
  {
    id: 11,
    name: 'Tofu Teriyaki',
    rating: 4.9,
    categories: [2, 3],
    priceRating: affordable,
    photo: images.tofu_teriyaki,
    duration: '35 - 40 min',
    menu: [
      {
        menuId: 11,
        name: 'Tofu Teriyaki',
        photo: images.tofu_teriyaki,
        description: 'Tofu, soya sauce, broccoli, spinach',
        calories: 375,
        price: 14,
        carbs: 48,
        protien: 48,
        fats: 15,
      },
    ],
  },
  {
    id: 12,
    name: 'Protien Balls',
    rating: 4.9,
    categories: [1, 4],
    priceRating: affordable,
    photo: images.protein_balls,
    duration: '35 - 40 min',
    menu: [
      {
        menuId: 12,
        name: 'Protien Balls',
        photo: images.protein_balls,
        description: 'Flour, chocolate chip, rasberries',
        calories: 84,
        price: 4.95,
        carbs: 6.9,
        protien: 9,
        fats: 3,
      },
    ],
  },
  {
    id: 13,
    name: 'Jerk Chicken',
    rating: 4.9,
    categories: [2, 3],
    priceRating: affordable,
    photo: images.jerk_chicken,
    duration: '35 - 40 min',
    menu: [
      {
        menuId: 13,
        name: 'Jerk Chicken',
        photo: images.jerk_chicken,
        description: 'Chicken thighs, brown rice, himalayan salt',
        calories: 444,
        price: 8.95,
        carbs: 2.2,
        protien: 46,
        fats: 14,
      },
    ],
  },
  {
    id: 14,
    name: 'Southern Fried Chicken',
    rating: 4.9,
    categories: [2, 3],
    priceRating: affordable,
    photo: images.southern_fried_chicken,
    duration: '35 - 40 min',
    menu: [
      {
        menuId: 14,
        name: 'Southern Fried Chicken',
        photo: images.southern_fried_chicken,
        description: 'chicken breast, plain bread crumbs, himalayan salt',
        calories: 527,
        price: 8.95,
        carbs: 69,
        protien: 48,
        fats: 5.3,
      },
    ],
  },
  {
    id: 15,
    name: 'Superfood Salad',
    rating: 4.9,
    categories: [2],
    priceRating: affordable,
    photo: images.superfood_salad,
    duration: '35 - 40 min',
    menu: [
      {
        menuId: 15,
        name: 'Superfood Salad',
        photo: images.superfood_salad,
        description:
          'White & black quinoa, butternut squash, pepper, cherry tomatoes',
        calories: 390,
        price: 7.95,
        carbs: 48,
        protien: 13,
        fats: 11.8,
      },
    ],
  },
];

export default { foodData, affordable, fairPrice, expensive }